### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by ZXHubs** [lvwzhen/medicine#15]
修改建议 
标题：原研药（含进口）药品目录 
修改说明：有一些进口药不一定是原研药，这样改正比较合适。 
— 
内容：大约500多种药品，本网站会实时更新原研药（含进口）药品目录。数据来源于各大药企官网等平台，仅供参考。不管是处方药Rx还是非处方药OTC，请务必在医师的指导下使用。 
修改说明：建议说明药物要在医师指导下使用，而不是按照说明书使用。这里绝大多数是Rx药物而非OTC药物。
— 
最后一列的列名“标签”改为“相关疾病与药品制剂类型”更为合适。 
— 
关于辉瑞和晖致，首先这不是一家公司，所以在希舒美这个药品这里请务必写清楚，晖致是由迈蓝和辉瑞普强合并而成。这一条：阿奇霉素片	希舒美	晖致制药（原辉瑞）。正确的是把括号中的原辉瑞给删除掉。 
— 
还有关于这个目录中，我建议新增 【上市药企】列，【上市药企】和【生产药企】有可能不是一家公司，我发现这里头有的药【生产药企】早就已经不是这一家公司了。  所有的带有【仿制药一致性评价】的均不是原研药。比如目录中的【阿莫西林克拉维酸钾干混悬剂	奥先	澳美制药】和【阿德福韦酯胶囊	名正	江苏正大天晴药业股份有限公司（泰中合资）】这两个药物的上明确带有此标签。所以参与贡献的小伙伴也请一起核对一下。但凡是带这个标签的一律要移除此目录清单。

剩余的商品名我补充一部分： 
* 多潘立酮混悬液和片剂的商品名均叫 吗丁啉® 
* 中美上海施贵宝制药有限公司 建议后面补充 百时美施贵宝 详见官网：https://www.bms.com/cn/about-us.html 百时美施贵宝在中国有四个法人单位, 分别是： * 中美上海施贵宝制药有限公司（“中美上海施贵宝”）成立于1982年10月14日，由美国百时美施贵宝公司与上海医药（集团）有限公司以及中国医药对外贸易总公司共同投资成立，是中国改革开放以后成立的第一家中美合资制药企业。1985年10月正式投入生产。 * 百时美施贵宝（上海）贸易有限公司成立于1997年，进出口各类医药产品、原材料和设备。 * 百时美施贵宝（中国）投资有限公司成立于1998年。 * 百时美施贵宝（中国）医药有限公司成立于2013年。

商品名：博路定®	恩替卡韦片 
商品名称：蒙诺®	福辛普利钠片
 商品名称：康纳乐®（现在这个药物已经注销了）	复方曲安奈德乳膏 
商品名称：开博通®（现在这个药物已经注销了）	卡托普利片 
普拉固（这个也没了）	普伐他汀钠片
 施复捷（这个也没了）	头孢丙烯片 
商品名称：泛捷复®	头孢拉定胶囊 
格华止®（不过上市时默克持有的）	盐酸二甲双胍片
铝碳酸镁片现在叫铝碳酸镁咀嚼片，商品名：达喜® 
盐酸莫西沙星片，商品名：拜复乐® 
布洛芬缓释胶囊，商品名：芬必得® 
草酸艾司西酞普兰片，商品名：来士普® 
洛索洛芬钠片，商品名：乐松® 
左氧氟沙星片，商品名：可乐必妥® 
硝酸咪康唑乳膏 硝酸咪康唑散 硝酸咪康唑栓 硝酸咪康唑阴道软胶囊，商品名都叫：达克宁® 
妥布霉素滴眼液 妥布霉素眼膏，商品名都叫：托百士® 
妥布霉素地塞米松滴眼液 妥布霉素地塞米松眼膏 ，商品名都叫：典必殊® 
达力士®：卡泊三醇搽剂 
达力士®：卡泊三醇软膏 
卡泊三醇倍他米松凝胶（赛美尔®） 
卡泊三醇倍他米松软膏（得肤宝®） 
立思丁® ：夫西地酸乳膏 
普特彼®：他克莫司软膏（0.1%） 
普特彼®：他克莫司软膏（0.03%） 
（阿法骨化醇软胶囊	阿法迪三	以色列梯瓦制药工业有限公司）这是仿制药，原研药是LEO制药的依安凡®  
商品名带上®  
先说这么些吧。还有好多呢😂，你参考的这份文档质量有点差。不过现在的环境，确实难查这样的资料，有人整理就很不错了。等有空了再慢慢联系你，把剩余的商品名补齐。

**Comment by lvwzhen** [comment]
已更新，感谢
