### ISSUE TITLE
更简洁的部署或有blog中更好的嵌入方式

### ISSUE THREAD

**Issue by imevancn** [lvwzhen/medicine#27]
我不是纯技术，所以不知道在技术上是否可以实现，让blog小白也能把这个功能放在自己的blog中，或者更容易的自行部署？
最终目的是让这个功能让更多的人看到，让它帮助更多的人，我相信大家也是这么想的，不然也不会做这个。我只提出一种可能性，仅供参考。

**Comment by imevancn** [comment]
如果可以直接在blog页面设置：插件？直接代码引用？我不知道

**Comment by flypigxyz** [comment]
如果能加上功能主治，用法用量，就更好了，越详细越好。同意楼上，做成插件嵌入自己的博客中，更好。

**Comment by Kongloli** [comment]
如果加上用法用量就要把药品规格也加上了，有些药的用法用量是比较复杂的。

**Comment by lvwzhen** [comment]
请遵医嘱用药，并在医师指导下使用药物。
请保持本项目的中立性，暂不会增加功效，用药等说明。
谢谢。
